apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  values:
    global:
      multiCluster:
        # Provided to ensure a human readable name rather than a UUID.
        clusterName: "cn-vikraya-ecommerce-us-central1-a-cluster-1" # {"$ref":"#/definitions/io.k8s.cli.substitutions.cluster-name"}
