apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  profile: empty
  hub: gcr.io/gke-release/asm # {"$ref":"#/definitions/io.k8s.cli.setters.anthos.servicemesh.hub"}
  tag: 1.17.2-asm.1 # {"$ref":"#/definitions/io.k8s.cli.setters.anthos.servicemesh.tag"}
  meshConfig:
    trustDomainAliases: # {"$ref":"#/definitions/io.k8s.cli.setters.anthos.servicemesh.trustDomainAliases"}
    - "vikraya-ecommerce.svc.id.goog"
    - "vikraya-ecommerce.hub.id.goog"
    trustDomain: vikraya-ecommerce.svc.id.goog # {"$ref":"#/definitions/io.k8s.cli.setters.anthos.servicemesh.trustDomain"}
    defaultConfig:
      proxyMetadata:
        GKE_CLUSTER_URL: "https://container.googleapis.com/v1/projects/vikraya-ecommerce/locations/us-central1-a/clusters/cluster-1" # {"$ref":"#/definitions/io.k8s.cli.setters.anthos.servicemesh.idp-url"}
        GCP_METADATA: "vikraya-ecommerce|471402206788|cluster-1|us-central1-a" # {"$ref":"#/definitions/io.k8s.cli.substitutions.gke-metadata"}
        CA_PROVIDER: "GoogleCA"
        PLUGINS: "GoogleTokenExchange"
        USE_TOKEN_FOR_CSR: "true"
        GCE_METADATA_HOST: "metadata.google.internal"
    # Locality load balancing is not supported
    localityLbSetting:
      enabled: false
  components:
    base:
      enabled: true
    egressGateways:
    - enabled: false
      name: istio-egressgateway
      k8s:
        hpaSpec:
          maxReplicas: 5
          minReplicas: 2
    ingressGateways:
    - enabled: false
      name: istio-ingressgateway
      k8s:
        hpaSpec:
          maxReplicas: 5
          minReplicas: 2
    # The default profile is tuned to fit on smaller clusters.
    # Increase cpu req to ensure we can handle larger scale clusters.
    pilot:
      enabled: true
      k8s:
        resources:
          requests:
            cpu: 500m
        hpaSpec:
          minReplicas: 2
        replicaCount: 2
        env:
        - name: GKE_CLUSTER_URL
          value: "https://container.googleapis.com/v1/projects/vikraya-ecommerce/locations/us-central1-a/clusters/cluster-1" # {"$ref":"#/definitions/io.k8s.cli.setters.anthos.servicemesh.idp-url"}
        - name: GCP_METADATA
          value: "vikraya-ecommerce|471402206788|cluster-1|us-central1-a" # {"$ref":"#/definitions/io.k8s.cli.substitutions.gke-metadata"}
        - name: SPIFFE_BUNDLE_ENDPOINTS
          value: "vikraya-ecommerce.svc.id.goog|https://storage.googleapis.com/mesh-ca-resources/spiffe_bundle.json" # {"$ref":"#/definitions/io.k8s.cli.substitutions.spiffe-bundle-endpoints"}
        - name: ENABLE_STACKDRIVER_MONITORING
          value: "true" # {"$ref":"#/definitions/io.k8s.cli.setters.anthos.servicemesh.controlplane.monitoring.enabled"}
        - name: TOKEN_AUDIENCES
          value: "istio-ca,vikraya-ecommerce.svc.id.goog" # {"$ref":"#/definitions/io.k8s.cli.substitutions.token-audiences"}
        - name: PILOT_ENABLE_CROSS_CLUSTER_WORKLOAD_ENTRY
          value: "true"
  values:
    # Enable telemetry v2 backend by Stackdriver.
    # Prometheus is also supported with --set values.telemetry.v2.prometheus.enabled=true --set prometheus.enabled=true
    telemetry:
      enabled: true
      v2:
        enabled: true
        prometheus:
          enabled: false
        stackdriver:
          enabled: true
          inboundAccessLogging: "FULL"
          outboundAccessLogging: "ERRORS_ONLY"
          topology: true
    sidecarInjectorWebhook:
      rewriteAppHTTPProbe: true
    global:
      caAddress: "meshca.googleapis.com:443"
      pilotCertProvider: kubernetes
      sts:
        servicePort: 15463
      sds:
        token:
          aud: "vikraya-ecommerce.svc.id.goog" # {"$ref":"#/definitions/io.k8s.cli.setters.anthos.servicemesh.trustDomain"}
      multiCluster:
        # Provided to ensure a human readable name rather than a UUID.
        clusterName: "cn-vikraya-ecommerce-us-central1-a-cluster-1" # {"$ref":"#/definitions/io.k8s.cli.substitutions.cluster-name"}
      meshID: "proj-471402206788" # {"$ref":"#/definitions/io.k8s.cli.substitutions.mesh-id"}
      network: "vikraya-ecommerce-default" # {"$ref":"#/definitions/io.k8s.cli.setters.gcloud.compute.network"}
    gateways:
      istio-ingressgateway:
        # Enable gateway injection
        injectionTemplate: gateway
      istio-egressgateway:
        # Enable gateway injection
        injectionTemplate: gateway
