apiVersion: v1
kind: Service
metadata:
   name: auth-service
   namespace: auth-ns
spec:
   selector:
       app: authentication-server
   type: ClusterIP
   ports:
   - name: auth-service-port
     port: 8080
  