apiVersion: v1
kind: Service
metadata:
   name: cart-service
   namespace: cart-ns
spec:
   selector:
       app: cart-manager-server
   type: ClusterIP
   ports:
   - name: cart-service-port
     port: 8080
  