apiVersion: v1
kind: Service
metadata:
   name: catalog-service
   namespace: catalog-ns
spec:
   selector:
       app: catalog-manager-server
   type: ClusterIP
   ports:
   - name: catalog-service-port
     port: 8080
  