{{- if .Values.catalogService.create }}
apiVersion: v1
kind: Service
metadata:
  name: catalog-service
  namespace: {{ .Values.catalogService.namespace }}
spec:
  selector:
    app: {{ .Values.catalogService.name }}
  type: ClusterIP
  ports:
  - name: catalog-service-port
    port: 8080
{{- end }}