{{- if .Values.catalogService.create }}
apiVersion: v1
metadata:
   name:  {{.Values.catalogService.serviceAccountName}}
   namespace: {{.Values.catalogService.namespace}}
   annotations:
       iam.gke.io/gcp-service-account: {{.Values.gcp_service_account}}
kind: ServiceAccount
{{- end }}
