{{- if .Values.authService.create }}
apiVersion: v1
metadata:
   name:  {{ .Values.authService.serviceAccountName }}
   namespace: {{.Values.authService.namespace}}
   annotations:
       iam.gke.io/gcp-service-account: {{.Values.gcp_service_account}}
kind: ServiceAccount
{{- end }}