apiVersion: apps/v1
metadata:
   name: frontend 
   namespace: frontend
kind: Deployment
spec:
    replicas: 1
    selector:
      matchLabels:
          app: frontend 
    template:
       metadata:
           labels:
            app: frontend
       spec:
        serviceAccountName: frontend-sa
        containers:
        - name: cnt-1
          envFrom:
            - configMapRef:
                name: configmap-frontend
            - secretRef:
                name: redis-config
            - secretRef:
                 name: vertex-ai-creds

          image:  us-docker.pkg.dev/vikraya-ecommerce/vikraya-ecommerce/frontend:latest
          ports:
          - containerPort: 8080
            name: metrics
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi