apiVersion: monitoring.googleapis.com/v1
kind: PodMonitoring
metadata:
  name: prom-frontend
  namespace: frontend

spec:
  selector:
    matchLabels:
     app: frontend

  endpoints:
  - port: 8080
    path: "/metrics" 
    interval: 30s