apiVersion: v1
data:
  REDIS_SERVER_AUTH_STRING: NGQ1NmZkZGMtNjNlYS00ZjlkLTg4YzktZmZiMGFmZWM2YjY5
  REDIS_SERVER_IP_ADDRESS: MTcyLjE2LjIuMTE=
  REDIS_SERVER_PORT: NjM3OQ==
kind: Secret
metadata:
 
  name: redis-config
  namespace: frontend
  
type: Opaque
