apiVersion: v1
kind: Service
metadata:
   name: frontend-service 
   namespace: frontend 
spec:
   selector:
       app: frontend
   type: LoadBalancer
   ports:
   - name: frontend-port
     targetPort: 8080
     port: 8080

  