{{- if .Values.frontend.create }}
apiVersion: v1
data:
   VECTOR_SEARCH_API_ENDPOINT: {{ .Values.api_gateway_config.url }}
   VECTOR_SEARCH_API_KEY: {{ .Values.api_gateway_config.apiKey }}

kind: Secret
metadata:
 
  name: redis-config
  namespace: {{ .Values.frontend.namespace }}
  
type: Opaque
{{- end }}