{{- if .Values.frontend.create }}
apiVersion: v1
data:
  REDIS_SERVER_AUTH_STRING:   {{ .Values.redis_config.auth_string }}
  REDIS_SERVER_IP_ADDRESS: {{ .Values.redis_config.ip_address }}
  REDIS_SERVER_PORT: {{ .Values.redis_config.port }}
kind: Secret
metadata:
 
  name: redis-config
  namespace: {{ .Values.frontend.namespace }}
  
type: Opaque
{{- end }}