{{- if .Values.frontend.create }}
apiVersion: v1
metadata:
   name:  {{ .Values.frontend.serviceAccountName }}
   namespace: {{ .Values.frontend.namespace }}
   annotations:
      iam.gke.io/gcp-service-account: {{ .Values.gcp_service_account }} 
   
kind: ServiceAccount
{{- end }}
