{{- if .Values.orderManager.create }}
apiVersion: v1
metadata:
   name:  {{ .Values.orderManager.serviceAccountName }}
   namespace: {{ .Values.orderManager.namespace }}
   annotations:
       iam.gke.io/gcp-service-account: {{ .Values.gcp_service_account }} 
kind: ServiceAccount
{{- end }}