{{- if .Values.cartService.create }}
apiVersion: v1
metadata:
   name:  {{ .Values.cartService.serviceAccountName }}
   namespace: {{ .Values.cartService.namespace }}
   annotations:
       iam.gke.io/gcp-service-account: {{.Values.gcp_service_account}}
kind: ServiceAccount
{{- end }}